name: Release Plugin

on:
  push:
    branches:
      - main # Или master, в зависимости от вашей основной ветки

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Даем права на запись для создания/обновления релизов
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: gradle build

      - name: Get plugin version
        id: properties
        run: |
          VERSION=$(grep 'pluginVersion' gradle.properties | cut -d'=' -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.properties.outputs.VERSION }}"
          name: "Release v${{ steps.properties.outputs.VERSION }}"
          body: "Automatic release for version ${{ steps.properties.outputs.VERSION }}"
          # Используем wildcard (маску) для надежного поиска JAR-файла
          files: "build/libs/*.jar"
          fail_on_unmatched_files: true
